### PR TITLE
Feature/subclass print

### PR DESCRIPTION
**Pull request by datdamnzotz**
Changed to mutiline in PDF's and added check for subclass-name being blank.

### CODE REVIEW

**Comment by datdamnzotz** [comment]
Related to
Implements #80 (with deamons help)

**Comment by datdamnzotz** [comment]
Formats to: 
image

**Comment by Demonsthere** [comment]
Nice catch, I have been trying to modify the templates but with no luck :(.
How does it look like when each class entry is in a new line? I worry that this will clatter too much

**Comment by datdamnzotz** [comment]
It is limited to 3 crlf  
image
that actually has 4 in it.

**Review by codeGlaze — APPROVED** [review]
Works locally 👍

**Pull request merged**
