### PR TITLE
Fixs for hitdice

### LINKED ISSUE #120: Hit Dice representation problems in character sheet
**Describe the bug**
An hit die is not a pure die. and the grouping is wrong

**To Reproduce**
Create any character with at least 1 level

**Expected behavior**
show something along the lines of:
3x (1d8+1) / 3x (1d12+1)

image

Writing each die of each size with their modifier as a different entity and keeping the contitution modifier as a "single die" thing. So players know they have some dice of one kind and some of another kind.

As far as i remember there is no way for a character to have hit die with different constitution/bonus values depending on the class, but even if the class/subclass redefined the hit die for that class by adding a "+1 per level hit points" that usually has no effect on the hit die, just on the total hit points, so i'm ignoring such fringe cases.

**Screenshots Of The Current Situation**

the used layout is a pure XdY for single class or WdX / YdZ for multiclass depending on how many classes the character has, which could get lengthy i've made 2 random quick characters of 2 classes with 3 levels each to show the problem.

example 1:

2 classes with different hit die size. as you can see nowhere is the constitution stated, and with a layout such as 3d8/3d12 writing the +1 constitution as "3d8+1/3d12+1" or "3d8/3d12 +1" would probably just confuse players

image
This should read: 3x (1d8+1) / 3x (1d12+1)

example 2:

2 classes with the same hit die size. These things should be grouped as we're talking about hit dice here, not class levelling. this should not read 3d8/3d8 

image
This should read: 6x (1d8+1)

### PR DESCRIPTION
**Pull request by datdamnzotz**
Fixes #120

### CODE REVIEW

**Comment by Demonsthere** [comment]
Could you post an image showing the current state? I saw the debate in the issue, and IMHO, there is little sense in splitting it per class (like separate for ranger or fighter) that share the same hit dice.

**Comment by datdamnzotz** [comment]
image

**Comment by marloso2** [comment]
I reckon it'd be better to have a script in place that checks for two of the same type of dice and merges it into one, rather than listing each class separately. It doesn't make a difference to the hit dice whether it's from fighter or from ranger, what matters is the values. It'd be easy to do with the pre-coded classes but applying this to homebrew ones would be a bit more challenging.

**Comment by datdamnzotz** [comment]
I was playing around with that, but it's much harder than I thought.

**Comment by marloso2** [comment]
I'll give it a try myself, let you know if I get anything

**Comment by codeGlaze** [comment]
Can you just map it to an array/hash using the hitdie as the index?

**Comment by datdamnzotz** [comment]
um yah I'll need help with that...  in C# it's easy

**Comment by KingMob** [comment]
@johnliss OK, check it out now.

**Review by KingMob — APPROVED** [review]
LGTM

**Pull request merged**
