### PR TITLE
Spell card add materials

### PR DESCRIPTION
**Pull request by datdamnzotz**
Old
image

New
image

### CODE REVIEW

**Comment by datdamnzotz** [comment]
Implements #100

**Review by Demonsthere — CHANGES_REQUESTED** [review]
Hi there. Always nice to make your reviews during breakfast :D. I like the components change, but I think it is more readable when the DC and spell bonus are on the bottom as in the original. 
Could you move it to the bottom like:

‘’’
—-
DC: X
Spell modificator: Y
‘’’

**Comment by datdamnzotz** [comment]
2 request for top, 1 request for bottom  I can't please everyone LOL

**Comment by datdamnzotz** [comment]
see https://www.reddit.com/r/orcpub/comments/awlsfh/spell_cards/

**Comment by datdamnzotz** [comment]
Now looks like: 
image

**Comment by datdamnzotz** [comment]
oops wrong branch deleted.. Re-opened.

**Comment by codeGlaze** [comment]
Is it worthwhile to add a checkbox/flag to arrange the DC/spell mod to the top or bottom?

We all know we and our fellow geeks can be very particular.

**Review by Demonsthere — APPROVED** [review]

**Pull request merged**
