### PR TITLE
Fixed compile issue in pdf.clj that it could not find stacktrace

### PR DESCRIPTION
**Pull request by doug-w**

### CODE REVIEW

**Comment by MeanderingCode** [comment]
Did build fail for you every time without this? I am curious if this is entirely deterministic or if there is some randomness to the build ordering.

Adding just the `clojure.pprint` to `src/clj/orcpub/email.clj` fixed the build on Docker Hub.

**Comment by Demonsthere** [comment]
We know that the build order is random or semi random and connected to the physical platform building it. This could be another corner case that we didn’t hit before

**Review by Demonsthere — APPROVED** [review]

**Comment by doug-w** [comment]
It failed 1 of the 2 times that I was watching it and has worked 5 of 5 since.

**Comment by MeanderingCode** [comment]
If this is non-reproduceable, I hesitate to add it. We I am honestly a bit baffled that in clojure some things seem to be imported globally while others explicitly, but if that's the language pattern, doing this opens the gates to importing everything willy nilly and breaking language patterns.

Since none of us know clojure, perhaps we ought to figure out the language standards around `require`s before proceeding.

If this continues to crop up, then it seems worth adding as a workaround.

**Comment by datdamnzotz** [comment]
I'm with @MeanderingCode I can't reproduce it.  We will reopen if necessary.

**Pull request closed without merging**
