### PR TITLE
Add Rar.'s Telepathic Bond to Wizard Spell List

### PR DESCRIPTION
**Pull request by LumaDevelopment**
Adding Rar.'s Telepathic Bond to the 5th Level Spell List for the Wizard. This is a test ID, hopefully it works!

### CODE REVIEW

**Comment by codeGlaze** [comment]
I would suggest touching the spells file, too.

Rename the spell to match the SRD "Telepathic Bond" (no reference to Rory at all).
Then rename the spell list version from `ror--s-telepathic-bond` to `telepathic-bond`.

Then we can see if everything explodes!

**Comment by LumaDevelopment** [comment]
@codeGlaze 
I've went ahead and renamed it to "Telepathic Bond", as you suggested.

**Comment by datdamnzotz** [comment]
While your in there... Fix the spelling here too : ]
https://github.com/Orcpub/orcpub/blob/793c7022a0839102210efe2e6e76201f60dccc6d/src/cljc/orcpub/dnd/e5/spells.cljc#L3189

**Review by datdamnzotz — APPROVED** [review]
Looks good.

**Pull request merged**
