### PR TITLE
Capitalised and pluralized Eldritch Invocations in the My Content tab

### PR DESCRIPTION
**Pull request by marloso2**
Adresses Issue #144

### CODE REVIEW

**Review by datdamnzotz — APPROVED** [review]
Nice catch, Approved.

**Comment by DivertedCircle** [comment]
Slight problem.
image

**Comment by marloso2** [comment]
Ahh @johnliss mind changing line 7078 in `src/cljs/orcpub/dnd/e5/views.cljs` back to `"eldritch invocation"`?

**Comment by datdamnzotz** [comment]
Your commit, lol own it brother!
https://github.com/Orcpub/orcpub/pull/145/commits/39964a591307a16d0fee2ea81d2c93980d6894da

**Pull request merged**
