### PR TITLE
Fix facebook logins

### PR DESCRIPTION
**Pull request by datdamnzotz**
Rem'd out the facebook login, because 1) it is broke, 2) needs configuring before using.

### CODE REVIEW

**Review by MeanderingCode — CHANGES_REQUESTED** [review]
I would see this wrapped in a conditional with configurability unless we can confirm that the standing code pulls in email addresses and would allow for traditional login / password reset with this gone.

**Comment by Demonsthere** [comment]
Is this the fb login used in uberjar or figwheel?

**Comment by datdamnzotz** [comment]
> I would see this wrapped in a conditional with configurability unless we can confirm that the standing code pulls in email addresses and would allow for traditional login / password reset with this gone.

DMV has ran this way since day 3-4.  FB logins need to be looked at and fixed, this is a temp workaround until that happens.  This just removes the login button from the login screen until that gets either fixed or a configurable that disables/enables with config.

**Comment by datdamnzotz** [comment]
> Is this the fb login used in uberjar or figwheel?

It is used in both. it is on the login screen.  See issue #61

**Pull request closed without merging**
