### PR TITLE
Fix missing monster Challenge Ratings

### LINKED ISSUE #41: Add Missing CRs to monster creator
There are a handful of CRs missing in the monster builder, they should be added.

### PR DESCRIPTION
**Pull request by datdamnzotz**
Fixes #41

### CODE REVIEW

**Review by codeGlaze — APPROVED** [review]

**Comment by MeanderingCode** [comment]
What is going on here? Clojure is byzantine, but this looks like all it does is filter out keys from the `monsters/challenge-ratings` if the value is non-positive?

**Comment by codeGlaze** [comment]
The change fixes the bug that only listed CRs that existed on pre-populated monsters. Which was not the entire CR range.

**Comment by datdamnzotz** [comment]
Yes, that is exactly what it does.  monsters5e/challenge-ratings has  CR XP.  I only needed the CR so it drops the XP.

**Comment by MeanderingCode** [comment]
And only for pairs where there is an XP, if I read that correctly?

**Comment by datdamnzotz** [comment]
pairs are defined [here](https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/monsters.cljc#L44)

**Pull request merged**
