### PR TITLE
Fix for homebrew not being loaded.

### LINKED ISSUE #386: Homebrew files not being loaded
**Describe the bug**
plugins is never initialized.

image

### PR DESCRIPTION
**Pull request by datdamnzotz**
## Description:

Fixes #386 

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

### CODE REVIEW

**Comment by codeGlaze** [comment]
How was this working prior without the let statement?

**Comment by datdamnzotz** [comment]
> How was this working prior without the let statement?

It was, my fault, the https://github.com/Orcpub/orcpub/commit/ef301ecc1d1013c6a79ab8b0499cbd2f0233e9dd 
took it out.

**Comment by codeGlaze** [comment]
Note to self: add a comment to that plugin bar so it stands out, haha.

**Review by codeGlaze — APPROVED** [review]

**Comment by datdamnzotz** [comment]
it was part of the google code and I didn't notice it when it took that part out  ; /

**Comment by codeGlaze** [comment]
Nah, it was just poorly separated.

Easy mistake to make. Crazy it wasn't noticed until now. Several patrons run the Homebrew orcbrews iirc

**Pull request merged**
