### PR TITLE
Upgrade FontAwesome to 5.14.0

### LINKED ISSUE #431: [Maintenance] - Upgrade FontAwesome to 5.14.0
Upgrade fontawesome to latest 5.14.0

### PR DESCRIPTION
**Pull request by datdamnzotz**
## Description:
Fixes #431 

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

### CODE REVIEW

**Comment by codeGlaze** [comment]
image

Holy crap,  1700 files touched?

**Comment by datdamnzotz** [comment]
> Holy crap, 1700 files touched?

Yup - that's correct with the adds/removes of the font-awesome directories.
It's a delete of `font-awesome-4.x` and an add of `font-awesome 5.14`

image

**Comment by codeGlaze** [comment]
Is this something that can just be pulled during build instead of tracked?

**Comment by datdamnzotz** [comment]
> Is this something that can just be pulled during build instead of tracked?

LOL do you want to do the brain surgery of that?  

We use like 7-10 icons from FA. (Carret up,download, bug, play, social icons, plus,pencil etc)
I have no desire to weed through all the css and find all the dependencies of those.

**Comment by codeGlaze** [comment]
I'll look into the cdn aspect

**Comment by Pireax** [comment]
I already saw some nodejs related files in the repo, is it required for building? If it is the dependency can also be included there.

**Comment by datdamnzotz** [comment]
> I'll look into the cdn aspect

I'd vote for a CDN, but they can go out of support, rather just have the code included in our base that way we choose when it gets updated/modified.

> I already saw some nodejs related files in the repo, is it required for building? If it is the dependency can also be included there.

No nodejs is required.  The zip I downloaded was from here.
https://fontawesome.com/download

Just a rip and replace of what was already there with a couple deprecation fixes.

Only reason to upgrade is to keep it current so we don't go out of phase with web browsers css support.
v4 was last updated 2017.

**Comment by Pireax** [comment]
Yeah it's good to keep things updated. What I meant to suggest is that maybe we could use nodes package manager `npm` to install font awesome instead of including it into the repository itself but it seems like a lot of setup from what I could find.

**Comment by datdamnzotz** [comment]
> Yeah it's good to keep things updated. What I meant to suggest is that maybe we could use nodes package manager `npm` to install font awesome instead of including it into the repository itself but it seems like a lot of setup from what I could find.

Sure if we can figure out how to update the code with breaking changes.
https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

Either that or it is part of the Dockerbuild

**Comment by datdamnzotz** [comment]
Better implementation in #432 We will go that route.

**Pull request closed without merging**
