### PR TITLE
Cleanup datomic image

### PR DESCRIPTION
**Pull request by Demonsthere**
**Description**
- Remove unzip installation, as it is in the base image
- Remove baked in config file 
- Move datomic to separate docker repo

### CODE REVIEW

**Comment by datdamnzotz** [comment]
Probably can remove the /docker/datomic/transactor.properties from the repo since you are wanting to use the one inside the datomic zip.

**Comment by Demonsthere** [comment]
I moved the `transactor.properties` file to `/deploy`, where we have the nginx.conf and other stuff we mount into containers

**Comment by datdamnzotz** [comment]
aw ok, I miss understood.

**Review by MeanderingCode — APPROVED** [review]
Looks good. Much cleaner with two repositories on Hub.
I like the changes to the image with the default sample and mounting in our version.

**Pull request merged**
