### PR TITLE
Add new Character Sheet based on IWD

### LINKED ISSUE #445: Adds new character sheet - Alternate version
**Motivation / Use Case**

Add new character sheet - Alternate Version

### PR DESCRIPTION
**Pull request by Jessomadic**
## Description: This adds more to the current CS on DMV with a new CS Based on IWD

**Related issue (if applicable):** fixes #<issue number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

### CODE REVIEW

**Review by Jessomadic — COMMENTED** [review]
Everything is updating correctly￼

**Review by datdamnzotz — CHANGES_REQUESTED** [review]
Let's not over write the existing character sheet

Let's add to it

I would propose we use a naming structure as something like:
Original renamed to:
fillable-char-**sheetstyle-1**-0-spells.pdf
fillable-char-**sheetstyle-1**-1-spells.pdf
...
Yours
fillable-char-**sheetstyle-2**-0-spells.pdf
fillable-char-**sheetstyle-2**-1-spells.pdf
...
The next flavor
fillable-char-**sheetstyle-3**-0-spells.pdf
fillable-char-**sheetstyle-3**-1-spells.pdf
...

So put back the originals in the new naming format - and add yours as fillable-char-**sheetstyle-2**-x-spells.pdf

**Comment by Jessomadic** [comment]
@datdamnzotz ￼what do you think of style0_spell0 For the new name structure? I feel like it's gonna be much easier to read that way for future additions￼￼

**Comment by datdamnzotz** [comment]
> @datdamnzotz ￼what do you think of style0_spell0 For the new name structure? I feel like it's gonna be much easier to read that way for future additions￼￼

@Jessomadic  
6 dozen half the other - long as we can pass a var to which one is being used (simple index 0 - old, 1 - yours, 2 - next...)
It is used here https://github.com/Orcpub/orcpub/blob/develop/src/clj/orcpub/routes.clj#L457

**Pull request closed without merging**
