### PR TITLE
Fix page overflow due to roll tooltips in character page

### LINKED ISSUE #421: Page overflow due to roll tooltips in character page
**Describe the bug**
The tooltips for the roll buttons take up space outside of the page even when not visible, this makes it such that the page is larger than the viewport and you can scroll horizontally, but there is nothing there. A function was created for all roll buttons and the code was refactored to use this function, tooltips are disabled for the roll button if on mobile (you can't hover over an item with touch input anyways).

image

### PR DESCRIPTION
**Pull request by Pireax**
## Description:
The tooltips for the roll buttons take up space outside of the page even when not visible, this makes it such that the page is larger than the viewport and you can scroll horizontally, but there is nothing there. A function was created for all roll buttons and the code was refactored to use this function, tooltips are disabled for the roll button if on mobile (you can't hover over an item with touch input anyways).

image

Fixes: #421 

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

### CODE REVIEW

**Review by datdamnzotz — DISMISSED** [review]
👍

**Comment by Pireax** [comment]
Still found some issues, please wait with merging

**Comment by datdamnzotz** [comment]
NP.  I won't release it till monday some time anyways, Weekends in the busy DND time : ]

**Review by datdamnzotz — DISMISSED** [review]
👍

**Review by datdamnzotz — APPROVED** [review]
👍

**Pull request merged**
