### PR TITLE
Redirect to port 443 when connecting to port 80 in the default docker…

### PR DESCRIPTION
**Pull request by doug-w**
… connection

### CODE REVIEW

**Comment by Demonsthere** [comment]
Hi,
Is there a reason we want to force ssl? I mean besides the obvious one, that it is better to have ssl than not :D?

**Review by Demonsthere — DISMISSED** [review]

**Comment by johnliss** [comment]
this shouldn't redirect to localhost.  It should redirect to the url the browser came in on

**Review by datdamnzotz — DISMISSED** [review]
it should redirect to https://$host$request_uri;  not https://localhost

server {
    listen 80 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}

**Review by Demonsthere — DISMISSED** [review]

**Review by codeGlaze — APPROVED** [review]

**Review by MeanderingCode — APPROVED** [review]
Hostname changes addressed. Thanks.

**Pull request merged**
